language: elixir
elixir:
  - 1.5
  - 1.6
  - 1.7
otp_release:
  - 19.3
  - 20.3
  - 21.0
matrix:
  exclude:
    - elixir: 1.5
      otp_release: 21.0
    - elixir: 1.7
      otp_release: 19.3
sudo: false
env:
  - MIX_ENV=test
before_script:
  - mix deps.get --only test
script:
  - mix coveralls.travis
  - mix dialyzer --plt
  - mix dialyzer --halt-exit-status
  - mix credo --strict
after_script:
  - mix deps.get --only docs
  - MIX_ENV=docs mix inch.report
